//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RechargeMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RechargeTb
    {
        
        public int Id { get; set; }
        
        public string MobileRecharge { get; set; }
        
        public Nullable<decimal> Amount { get; set; }
        public static List<RechargeTb> GetAllRecharge()
        {
            List<RechargeTb> rm = new List<RechargeTb>()
            {
                new RechargeTb(){Id=1,MobileRecharge="34376",Amount=499},
                 new RechargeTb(){Id=2,MobileRecharge="98876",Amount=799}
            };
            return rm;
        }
    }
}
