//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentTestMonday.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SignUpPage
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "UserName  is mandatory")]
        [StringLength(20, ErrorMessage = "cannot accept more than 20 alphabets")]
       
        public string UserName { get; set; }
        [Required(ErrorMessage = "Password  is mandatory")]
        public string Password { get; set; }
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
        [Required]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail address")]
        public string emailId { get; set; }
        [Required(ErrorMessage ="City is Mandatory")]
        [RegularExpression("^[a-zA-Zs]+$", ErrorMessage = "Invalid CityName")]
        public string City { get; set; }
    }
}
